//
// Created by chris on 26.04.21.
//

#ifndef NUMERISCHEMETHODENSTATISTISCHENPHYSIK_HELLOWORLD_H
#define NUMERISCHEMETHODENSTATISTISCHENPHYSIK_HELLOWORLD_H

// Starts the Project Hello World. Returns 0 if no error occurs.
int runHelloWorld();


#endif //NUMERISCHEMETHODENSTATISTISCHENPHYSIK_HELLOWORLD_H
