//
// Created by chris on 07.05.21.
//

#ifndef NUMERISCHEMETHODENSTATISTISCHENPHYSIK_TEST_H
#define NUMERISCHEMETHODENSTATISTISCHENPHYSIK_TEST_H


class test {
public:
    int n;
};


#endif //NUMERISCHEMETHODENSTATISTISCHENPHYSIK_TEST_H
